### ISSUE TITLE
Fix for : build() got an unexpected keyword argument 'stream' 

### ISSUE THREAD

**Issue by gunshi** [duckietown/sim-duckiebot-lanefollowing-demo#7]
```
$ docker-compose -f docker-compose-lf.yml pull && docker-compose -f docker-compose-lf.yml up
Pulling gym-duckietown-server (duckietown/gym-duckietown-server:latest)...
latest: Pulling from duckietown/gym-duckietown-server
Digest: sha256:d214592631fb1b5b5fff352917d12d7eb4d358d731e6fccf08f386a9fea6d168
Status: Image is up to date for duckietown/gym-duckietown-server:latest
Pulling rosmonitor (ros:kinetic-perception)...
kinetic-perception: Pulling from library/ros
Digest: sha256:4e7712e9532a8c430b3d13cfb22ec264936fc16cbb15a3af36f75a00af07b59e
Status: Image is up to date for ros:kinetic-perception
Building lanefollow
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 318, in ensure_image_exists
    self.build()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
TypeError: build() got an unexpected keyword argument 'stream'
```

FYI
Gets fixed by updating docker-compose to >1.19 by installing with directions from here:

https://docs.docker.com/compose/install/#prerequisites

(apt may give you an old version)

Thanks @breandan

**Comment by bhairavmehta95** [comment]
@gunshi @breandan is there a way to do this on Ubuntu18? Apt only upgrades to 1.17
